### ISSUE TITLE
rule with single negated domain not matched correctly

### ISSUE THREAD

**Issue by nbraem** [scrapinghub/adblockparser#1]
A rule with a single negated domain, like so: "adv$domain=~example.com" is very common, but is not matched correctly.

Here's a snippet to make the tests fail for file "test/test_parsing.py":

```python
    "adv$domain=~example.com": [
        ("http://example.net/adv", {'domain': 'otherdomain.com'}, True),
        ("http://somewebsite.com/adv", {'domain': 'example.com'}, False),
    ],
```

**Comment by nbraem** [comment]
How about adding the options to the regex? When matching you could build 1 string that includes the specified options and then just match it with the 1 big regex for all the rules?

Here's what I mean for the rule "adv$domain=~example.com":
```
# matches
re.match(r'u<.*adv.*>d<.*?(?<!example\.com)>', 'u<http://example.net/adv>d<otherdomain.com>')
# does not match
re.match(r'u<.*adv.*>d<.*?(?<!example\.com)>', 'u<http://example.net/adv>d<example.com>')
```

**Comment by kmike** [comment]
@nbraem thanks for the report, I'll take a look. 

> How about adding the options to the regex?
What are the benefits of creating such regexes?

**Comment by nbraem** [comment]
Benefit is that you don't need additional logic to match the options rule by rule.

**Comment by kmike** [comment]
Sorry for a long delay! It should be fixed now.
