### ISSUE TITLE
Help with easylist.txt

### ISSUE THREAD

**Issue by JoaoLages** [scrapinghub/adblockparser#11]
Any help on getting the filter rules from easylist.txt, please?
Also, wouldn't it be faster to use a dictionary/set instead of a list?

**Comment by kmike** [comment]
Hey @JoaoLages,

To get rules from easylist.txt file you should read it and pass its lines to AdblockRules, something like

```
with open('easylist.txt', 'rb') as f:
    raw_rules = f.read().decode('utf8').splitlines()

rules = AdblockRules(raw_rules)
```

For rules matching re2 regex engine is used, it is faster than checking all rules one-by-one. There may be ways to make it faster though; suggestions are welcome.
